parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Province:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Province/Domain/Entity'
                prefix: 'App\Province\Domain\Entity'
                alias: Province

            County:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/County/Domain/Entity'
                prefix: 'App\County\Domain\Entity'
                alias: County

            Commune:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Commune/Domain/Entity'
                prefix: 'App\Commune\Domain\Entity'
                alias: Commune

            Address:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Address/Domain/Entity'
                prefix: 'App\Address\Domain\Entity'
                alias: Address
